### ISSUE TITLE
Misc:  Hass.Agent on Windows does not display image?

### ISSUE THREAD

**Issue by digitaldias** [LAB02-Research/HASS.Agent#278]
Hello. 
This is probably more me than the product, but I've set up a shared folder in my NAS where I store snapshots from my webcamera. 
I would like to display these snapshots in a notification. 
The image URL that I am sending is a file url: 
`file://<my NAS>/docker/ha/snapshots/<mycamera>_latest.jpg`

The script that I am testing this with looks like: 
```yaml
service: notify.<my computer>
data:
  message: Oh noes, lookie here!
  title: Spooky times!
  data:
    image: file://<my computer>/docker/ha/snapshots/<my camera>_latest.jpg
```
The URL checks out fine in the browser but does not show in the windows notification. I only get the title and the text. 
I would love some hints as to what might be wrong, I searched through the documentation and issues here, but I couldn't find the answer. I am betting that it is something really silly though :)
