### ISSUE TITLE
Bug: Adjust-screen-brightness not working

### ISSUE THREAD

**Issue by nightfever77** [LAB02-Research/HASS.Agent#297]
I am trying to get this to work: [https://hassagent.readthedocs.io/en/latest/examples/adjust-screen-brightness/](url)
When adding the yaml.code for the mqtt light I am getting the message `Property brightness_command_template is not allowed`.
The light entity itself is working, but Monitorian does not react.
Is this method outdated?

**Comment by RaceX58** [comment]
I'm having the same problem.
I haven't found any solution at the moment.

Can someone please help us ?

**Comment by jardelhnascimento** [comment]
Hey! Don't know if this is still relevant but I was also having trouble with this example. I've managed to get this working with ClickMonitorDDC (I already used it and Monitorian was not working with my laptop display or my connected monitor). This program supports CLI commands and works with the example template. My problem is that the example is not very clear on the how to set everything up and some help links on HASS.Agent are broken.
Anyways, here how I set up this function:
1. Create a custom command with "Light" as the "Entity Type", leave the "Command" field empty.
![image](https://github.com/user-attachments/assets/5678ebe3-3e44-4650-a382-fa6c71919f51)

2. Click the "Show MQTT Action Topic" and copy it.
![image](https://github.com/user-attachments/assets/695f3db3-8d61-436a-96c6-69edda170124)
![image](https://github.com/user-attachments/assets/4dcec263-2774-45a3-8a42-35e0a2bd9e46)
3. Create an MQTT Light entity in Home Assistant. I think the easiest way to do this is filling up the template bellow and pasting it on your Home Assistant `configuration.yaml` file.
Template:
```
mqtt:
  light:
    - name: "Your Friendly Screen Name"
      unique_id: "your_screen_name"
      object_id: "your_screen_name"
      command_topic: "PASTE YOUR COPIED MQTT COMMAND TOPIC HERE"
      brightness_command_topic: "PASTE YOUR COPIED MQTT COMMAND TOPIC HERE"
      brightness_command_template: "%LOCALAPPDATA%\\Microsoft\\WindowsApps\\Monitorian.exe /set {{ value }}" #If you are using Monitorian. Pay attention to escaped backlashes (\\) and quotes (\") IF you change this field.
      brightness_scale: 100
      on_command_type: 'brightness'
      icon: mdi:monitor-shimmer
```
4. After editing your `configuration.yaml` file, restart Home Assistant and a new "Light" entity with the name you specified should appear in your entity list. 

When you change the brightness Home Assistant will send an MQTT message to HASS.Agent using the `brightness_command_template` , substituting the `{{ value }}` for the value you just set.
You can debug the MQTT messages to make sure it is working right with MQTT-Explorer (pretty easy to use and even has a portable version so you don't even need to install anything)

I'm using ClickMonitorDDC, so I had to adjust the `brightness_command_template`  to `"\"C:\\Program Files (x86)\\ClickMonitorDDC\\ClickMonitorDDC_7_2.exe\" onboard b {{ value }}"`. In my ClickMonitorDDC configuration, I changed the name of my laptop screen to "onboard". Adjust this according to your configuration and instalation path
