### ISSUE TITLE
Misc: Help convert MB to GB

### ISSUE THREAD

**Issue by avenom** [LAB02-Research/HASS.Agent#407]
Please help me convert MB to GB in this code:

```
- platform: template
  sensors:
    storage_capacity_d:
      friendly_name: "Storage Capacity Drive D"
      unit_of_measurement: "MB"
      value_template: "{{ state_attr('sensor.avenompc_avenompc_storage_d', 'AvailableSpaceMB')}}"
```

Result: 181 953,0 MB

**Comment by ruifung** [comment]
```
- platform: template
  sensors:
    storage_capacity_d:
      friendly_name: "Storage Capacity Drive D"
      unit_of_measurement: "GB"
      value_template: "{{ state_attr('sensor.avenompc_avenompc_storage_d', 'AvailableSpaceMB') | float / 1000}}"
```
In case you're not aware, you *can* do math in HA templates. 
Note: I made the changes off the top of my head, if it don't work, there's probably a typo somewhere.

Also note, since your example is in MB (not MiB), you divide by 1000 to get GB.
If the source data is actually in binary units (i.e. MiB), divide by 1024 to get GiB instead.

**Comment by avenom** [comment]
> ```
> - platform: template
>   sensors:
>     storage_capacity_d:
>       friendly_name: "Storage Capacity Drive D"
>       unit_of_measurement: "GB"
>       value_template: "{{ state_attr('sensor.avenompc_avenompc_storage_d', 'AvailableSpaceMB') | float / 1000}}"
> ```
> 
> In case you're not aware, you _can_ do math in HA templates. Note: I made the changes off the top of my head, if it don't work, there's probably a typo somewhere.
> 
> Also note, since your example is in MB (not MiB), you divide by 1000 to get GB. If the source data is actually in binary units (i.e. MiB), divide by 1024 to get GiB instead.

Result: 181,953 GB

**Comment by ruifung** [comment]
maybe you need parentheses for that. Try plugging the template into the HA devtools template tester and play around with it until you get the output you want.

**Comment by avenom** [comment]
1. I generated a UUID for the sensor ([https://www.uuidgenerator.net/version4)](https://www.uuidgenerator.net/version4) and can now round up in the sensor properties in HA
2. Converted bytes to the binary system of gibibytes (GiB).

Not perfect, but it works.

Sample:
```
- platform: template
  sensors:
    storage_capacity_d:
      friendly_name: "Storage Capacity Drive D"
      unique_id: 30a103c2-3147-4de3-be98-3a9a80ed7fc3
      unit_of_measurement: "GB"
      value_template: "{{ state_attr('sensor.avenompc_avenompc_storage_d', 'AvailableSpaceMB') | float / 1073.741824 }}"
```

![storage-mebibyte_measurements](https://github.com/LAB02-Research/HASS.Agent/assets/17644125/0720690e-29e5-42a3-b683-ff227a447b1b)

![2024-04-13 17-30-10 Home Assistant](https://github.com/LAB02-Research/HASS.Agent/assets/17644125/54e01484-fc9b-4818-bb16-4a69f28b4bb8)

![2024-04-13 17-28-49 Home Assistant](https://github.com/LAB02-Research/HASS.Agent/assets/17644125/781a383d-0bf3-4747-9d68-9164d9c10cb6)
