### ISSUE TITLE
Bug: notification images aren't downloaded in case of certificate mismatch

### ISSUE THREAD

**Issue by andystewart999** [LAB02-Research/HASS.Agent#42]
Hi - for my particular deployment I use https with DuckDNS.  For some reason my company has put DuckDNS on a blocklist so any URL with DuckDNS in it is being blocked so I planned to use the local IP address instead.

Of course that means that the full URL doesn't match the certificate path so I assume that's why the actual picture isn't showing up for notifications (as it works perfectly well if I use an http source, or an https source with the correct URL.

A workaround might be to just ignore, or add an option to ignore, certificate errors?  At least for image URLs.

Cheers,
Andy

**Comment by andystewart999** [comment]
Thanks very much!

**Comment by LAB02-Admin** [comment]
Hey @andystewart999, I was busy adding the `ignore certificate errors for images` function in HASS.Agent (actually completed it), but afterwards I found out that's not the issue 😅 

It's because when you're using duckdns, you can't access HA locally anymore. I've fixed it by using the **NGINX Home Assistant SSL proxy** addon.

There were a few caveats I had to fix, I'll write them here so you won't have to (hopefully):

- Install **NGINX Home Assistant SSL proxy** addon
- Configure as follows:

```yaml
certfile: fullchain.pem
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
domain: your_domain.duckdns.org
hsts: max-age=31536000; includeSubDomains
keyfile: privkey.pem
```

- Start the addon, it'll give errors in the log, don't mind those
- You probably changed the `http` section of `configuration.yaml` for the duckdns addon, change it to the following:

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

- Reboot Home Assistant
- If you set port forwarding in your router, you need to change the destination port from `8123` to `443`
- You can ofc keep the source port the same, as long as it forwards to `443`

You should now be able to access your Home Assistant instance both throug the duckdns url and through its local IP, and use the local IP to retrieve notification images.

Let me know if you have any issues!
