### ISSUE TITLE
Misc:  Using the active window sensor as a condition?

### ISSUE THREAD

**Issue by n0tOdd** [LAB02-Research/HASS.Agent#75]
Are there any reason why the active window sensor can not be used as a condition in automations?
i have some automations that auto play pause kodi in my living room, but im missing a way for it to only fire when kodi is my active window

**Comment by LAB02-Admin** [comment]
No that should be usuable. Perhaps something like this:

```yaml
condition:
  condition: state
  entity_id: sensor.name_of_your_sensor
  state: "Name of your Window"
```

Haven't tried it, I'm away for the weekend.
