### ISSUE TITLE
Feature: Binary power sensor

### ISSUE THREAD

**Issue by sophof** [LAB02-Research/HASS.Agent#81]
**Is your feature request related to a problem? Please describe.**
Power status of the machine has to be deduced from availability

**Describe the solution you'd like**
A simple binary sensor that is on when the hass.agent is connected and otherwise off.

**Describe alternatives you've considered**
A template binary sensor that is off if a single sensor is _Unavailable_

**Additional context**
I'm a bit surprised this is not yet provided, so I may have simply missed it, but I would expect this to be basic functionality? I'm trying to switch to the agent form my own python solution and there I have programmed this functionality via last-will as follows:
``` python
import paho.mqtt.client as mqtt
import os
import power
import json

#Settings
#=====================================================
user = "xxx"
passwd = "xxx"
machine = "xxx"

#topics
powerstate_topic = f"computers/{machine}/power/state"
powercommand_topic = f"computers/{machine}/power/command"
discovery_topic_state = f"homeassistant/binary_sensor/mqtt_pc/{machine}_power_state/config"

#MQTT server
mqtt_ip = "192.168.1.14"
mqtt_port = 1883
mqtt_refresh = 5

#discovery
discovery_state_json = {
  "state_topic": powerstate_topic,
  "name": f"{machine} Power Status",
  "unique_id": f"{machine}_power_state",
  "device_class": "power",
  "payload_on": "on",
  "payload_off": "off",
  "device": {
    "identifiers": [
      f"{machine}_Power"
    ],
    "name": f"{machine} Power",
  }
}

#=====================================================

# Constants
topics = []

# The callback for when the client receives a CONNACK response from the server.
def on_connect(client, userdata, flags, rc):
    client.publish(discovery_topic_state, json.dumps(discovery_state_json),1,True)
    client.publish(powerstate_topic,'on',1,True) #This should resend the alive message whenever the computer (re)starts
    client.subscribe(topics)

def on_message(mosq, obj, msg):
    # This callback will be called for messages that we receive that do not
    # match any patterns defined in topic specific callbacks.
    print(msg.topic+" "+str(msg.qos)+" "+str(msg.payload))

# Generic setup function that adds a topic to the topics to be subscribed and configures the callback
def add_topic(self, topic, callback):
    topics.append([topic, 1])
    self.message_callback_add(topic, callback)
mqtt.Client.add_topic = add_topic

# Callbacks per topic
#=====================================================
client = mqtt.Client(client_id = machine)
client.on_connect = on_connect
client.on_message = on_message

client.add_topic(powercommand_topic, power.on_message)


# Connect and start loop
#=====================================================
client.will_set(powerstate_topic,'off',1,True) #ask server to publish state off whenever no ping is received
client.username_pw_set(user, passwd)
client.connect(mqtt_ip, mqtt_port, mqtt_refresh)
client.loop_forever()
```
So an '_on_' state is send whenever the client connects and and '_off_' is send whenever there's a disconnect via the last will.

I can use this for instance for a nice template switch:
``` yaml
- platform: template
  switches:
    xxx:
      value_template: "{{ states('binary_sensor.xxx_power_status') }}"
      turn_on:
        service: wake_on_lan.send_magic_packet
        data:
          mac: 'xx:xx:xx:xx:xx:xx'
          broadcast_address: xxx.xxx.xxx.xxx
      turn_off:
        service: button.press
        target:
          entity_id: button.xxx_sleep
```

**Comment by LAB02-Admin** [comment]
I think I get what you're going for, but could you tell me the added value of this over using a `wake_on_lan` entity:

```yaml
- platform: wake_on_lan
  name: "your_pc_name"
  mac: "00-00-00-00-00-00"
  host: 10.0.0.5
  broadcast_address: 10.0.0.255
  turn_off:
    service: switch.turn_on
    data:
      entity_id: switch.your_pc_hass_agent_shutdown_switch
```
