### ISSUE TITLE
Docs: adjust screen brightness using Monitoring

### ISSUE THREAD

**Issue by DivanX10** [LAB02-Research/HASS.Agent#86]
I currently use IOTLink to adjust the brightness of the computer monitor screen, but the author of the project abandoned the IOTLink project and am looking after this project, but I can't understand how you can use commands to adjust the brightness here. To make it clear what we are talking about and how it works, first it is better to read the [post](https://community.home-assistant.io/t/we-control-the-brightness-of-the-computer-monitor-screen/431351) on the Home Assistant forum.

Is it possible to adjust the brightness of the monitor screen in Hass Agent?

**Comment by LAB02-Admin** [comment]
Hey @DivanX10, that's a very interesting post, thanks for sharing! It can be done through HASS.Agent using a CustomCommand with an Action. I'll write a document post about it, so others can use it as well, and report back here when it's done :)

**Comment by DivanX10** [comment]
Figured out how to implement the adjustment of screen brightness through HassAgent. We create a team and choose anything, since it doesn't matter, but the color suits us

![image](https://user-images.githubusercontent.com/64090632/174493496-4b3bc583-46ec-40cf-bcdd-57aec22d09a8.png)

We create a light object using [mqtt light](https://www.home-assistant.io/integrations/light.mqtt) and prescribe as below. You can control the brightness of the monitor screen

```
mqtt:
  light:
    - name: "Living room: Monitor. Screen Brightness"
      unique_id: "pc_livingroom_monitor_brightness"
      object_id: "pc_livingroom_monitor_brightness"
      command_topic: "homeassistant/light/LIVINGROOM/pc_livingroom_screen_brightness/action"
      brightness_command_topic: "homeassistant/light/LIVINGROOM/pc_livingroom_screen_brightness/action"
      brightness_command_template: "%LOCALAPPDATA%\\Microsoft\\WindowsApps\\Monitorian.exe /set {{ value }}"
      brightness_scale: 100
      on_command_type: 'brightness'
      icon: mdi:monitor-shimmer
```

To keep the brightness level in the auxiliary element number and for the values to be equal, then you need to use this code

```
{{ state_attr("light.pc_livingroom_monitor_brightness", "brightness")|multiply(0.392)|round(0) }}
```

**Comment by LAB02-Admin** [comment]
Oh wow you are on fire! This is really great stuff @DivanX10, thank you for helping me and the community ❤️

**Comment by brietman** [comment]
Is this still the best way to change my monitor brightness within HA? I get it to work though. First I didn't understand why, but I didn't read https://hassagent.readthedocs.io/en/latest/commands/actions-usage-and-examples/ . When I use **show mqtt action** topic and changed the yaml code, it worked flawless. I have a multi monitor, so I added my monitor name shown in Monitorian to the command template.

The problem was that didn't understand what in the code was a reference to HASSagent and in HA. Hope this helps

```
mqtt:
  light:
    - name: "Dell helderheid"
      unique_id: "Dell_helderheid"
      object_id: "Dell_helderheid"
      command_topic: "<insert  "show mqtt action">"
      brightness_command_topic: "insert  "show mqtt action""
      brightness_command_template: "%LOCALAPPDATA%\\Microsoft\\WindowsApps\\Monitorian.exe /set DELL S3220DGF {{ value }}"
      brightness_scale: 100
      on_command_type: 'brightness'
      icon: mdi:monitor-shimmer
```

Thanks!
