### ISSUE TITLE
Sensor ActiveWindowSensor

### ISSUE THREAD

**Issue by DivanX10** [LAB02-Research/HASS.Agent#87]
There is an Active Window Sensor that allows you to monitor the running process. For each process, you need to create a separate Active Window Sensor with different names. This makes it inconvenient to track whether the game is running or not. There is no grouping of all processes into one sensor. Or alternatively, there is an activewindow sensor that shows which window is currently active, a very convenient and useful sensor. You can add a menu of keywords for this sensor and a list of sensor names to the program. For example, we specified the keywords HaloInfinite, 4 Engine, GoW, DOOMEternal and if the activewindow sensor has these names, then the game sensor will work, and if there are words youtube, potplayer, then the mediaplayer sensor will work, if there are words github, google, then the browser sensor will work.  That is, for the created sensor there should be a window with keywords and if there is a match, the sensor will work.

For example, monitoring running games. In IOTLink, it looks like this, where all the games fall into one sensor with one name and we do not need to produce multiple ActiveWindowSensor sensors as in HassAgent.

```
processes:
  - ACValhalla.exe
  - DOOMEternalx64vk.exe
  - HorizonZeroDawn.exe
  - HaloInfinite.exe
  - RAGE2.exe
  - GoW.exe
  - MetroExodus.exe
windows:
classnames:
configs:
  enabled: true
  discoverable: true
  advancedMode: false
  displayName: Games
  cacheable: true
  grouped: true
  compareType: 0
  interval: 10
```

I tried HassAgent to specify multiple processes and tried different options in one sensor, but it doesn't work. How can one sensor be used for multiple processes?

MetroExodus\GoW\HaloInfinite
MetroExodus, GoW, HaloInfinite
"MetroExodus","GoW", "HaloInfinite"

![image](https://user-images.githubusercontent.com/64090632/174121449-18e2c30c-3535-450c-bd17-c766ff5bc98b.png)

**Comment by DivanX10** [comment]
I have created sensors that work by keywords. We enter the keywords into the auxiliary element text and from such an object we have a reconciliation with the Active Window Sensor. If there are words in the sensor, it will be on, if there is no such word, it will be off. Keywords are indicated by | . This will allow you not to create a bunch of sensors with different processes in the HASS.Agent program itself and you can flexibly automate brightness adjustment, ambilight, color effects on coolers

![image](https://user-images.githubusercontent.com/64090632/174195048-fa9b5c5f-961e-4ba4-95b9-714f2f05457b.png)


Auxiliary elements are text for entering keywords and which will be used in the sensor to track which program is running a game, video player or browser

```
input_text:
  pc_livingroom_games_keywords:
    name: 'Living room: Computer. Games. Keywords'
    min: 0
    max: 100000
    icon: mdi:google-controller

  pc_livingroom_videoplayer_keywords:
    name: 'Living room: Computer. Video player. Keywords'
    min: 0
    max: 100000
    icon: mdi:video

  pc_livingroom_browser_keywords:
    name: 'Living room: Computer. Browser. Keywords'
    min: 0
    max: 100000
    icon: mdi:web
```



We are creating sensors ourselves that will show the type of category that we are using at the moment
```
#Sensor Living Room: Computer. Game
sensor:
  - platform: template
    sensors:
      hassagent_pc_livingroom_running_game:
        friendly_name: "Living room: Computer. Game"
        icon_template: mdi:google-controller
        value_template: >
            {% set activewindow = states("sensor.pc_livingroom_activewindow") %}
            {% set games = states("input_text.pc_livingroom_games_keywords") %}
            {% if activewindow | string is search(find=games) %} on
            {% else %} off
            {% endif %}


#Sensor Living Room: Computer. Video Player
  - platform: template
    sensors:
      hassagent_pc_livingroom_running_videoplayer:
        friendly_name: "Living room: Computer. Video Player"
        icon_template: mdi:video
        value_template: >
            {% set activewindow = states("sensor.pc_livingroom_activewindow") %}
            {% set videoplayer = states("input_text.pc_livingroom_videoplayer_keywords") %}
            {% if activewindow | string is search(find=videoplayer) %} on
            {% else %} off
            {% endif %}


#Sensor Living Room: Computer. Browser
  - platform: template
    sensors:
      hassagent_pc_livingroom_running_browser:
        friendly_name: "Living room: Computer. Browser"
        icon_template: mdi:web
        value_template: >
            {% set activewindow = states("sensor.pc_livingroom_activewindow") %}
            {% set browser = states("input_text.pc_livingroom_browser_keywords") %}
            {% if activewindow | string is search(find=browser) %} on
            {% else %} off
            {% endif %}
```
